bump_version: null
lint:
  nextflow_config:
    - params.input
nf_core_version: 3.0.0.dev0
org_path: null
repository_type: pipeline
nextflow_config:
  - params.input
template:
  author: TBD
  description: Whole-slide multiplexed microscopy image analysis
  force: false
  is_nfcore: true
  name: mcmicro
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 2.0.0
update: null
